#!/usr/bin/env bash

COUNT=0
PASSED=0

for file in $(find ./tests/ -name "*.c"); do
	echo "$file" | grep "str" > /dev/null
	if [ $? -ne 0 ]; then
		COUNT=$(($COUNT + 1))
		TARGET=$(echo  "$file" | grep -oP "[^/]*(?=\.c)")
		echo -ne "${TARGET}\t: "
		echo -e "c\nq" | make ARCH=riscv32-nemu ALL=${TARGET} run > /tmp/.autotest_cputests
		cat /tmp/.autotest_cputests | grep -oP "HIT \w* TRAP"
		cat /tmp/.autotest_cputests | grep -oP "ABORT.+$"
	fi
done
