// Generated by CIRCT firtool-1.135.0
`ifndef layers_CPU_Verification_Assert	// src/main/scala/empty/CPU.scala:36:7
  `define layers_CPU_Verification_Assert
  `include "layers-CPU-Verification.sv"	// src/main/scala/empty/CPU.scala:36:7
`endif // not def layers_CPU_Verification_Assert
